const router = require('express').Router(),
    { find, findwallethistory, findcashouthistory, paymentdetail , findpaymentdetail, subscommission, filterwallet, filtergrinding,filtertransaction, findgrindinghistory, findtransactionhistory, buymmt, buymmc, mytoken, mytokenbuyhistory, tokenwithdrawhistory, buysubscription, totaltokens, deposittoken, mydeposittokenhistory, withdrawtoken, mywithdrawaltokenhistory, ifwithdrawerror} = require('../Gamecontrollers/Wallets'),
    { protectplayer } = require('../Gamemiddleware/index')
    
router 
    .get('/find', protectplayer, find)
    .get('/findwallethistory', protectplayer, findwallethistory)
    .get('/findcashouthistory', protectplayer, findcashouthistory)
    // .get('/findcashouthistory1', protectplayer, findmanualcashouthistory)
    .post('/paymentdetail', protectplayer, paymentdetail)
    .get('/findpaymentdetail', protectplayer, findpaymentdetail)
    .get('/totalcommission', protectplayer, subscommission)
    .post('/filterwallet', protectplayer, filterwallet)
    .get('/findtransactionhistory', protectplayer, findtransactionhistory)
    .get('/findgrindinghistory', protectplayer, findgrindinghistory)
    .post('/filtertransaction', protectplayer, filtertransaction)
    .post('/filtergrinding', protectplayer, filtergrinding)
    .post('/buymmt', protectplayer, buymmt)
    .post('/buymmc', protectplayer, buymmc)
    .get('/mytoken', protectplayer, mytoken)
    .get('/tokenbuyhistory', protectplayer, mytokenbuyhistory)
    .post('/tokenwithdrawhistory', protectplayer, tokenwithdrawhistory)
    .post('/buysubscription', protectplayer, buysubscription)
    .get("/totaltoken",protectplayer, totaltokens)
    .post("/deposittoken", protectplayer, deposittoken)
    .get("/deposithistory", protectplayer, mydeposittokenhistory)
    .post("/withdrawtoken", protectplayer, withdrawtoken)
    .get("/withdrawhistory", protectplayer, mywithdrawaltokenhistory)
    .post("/withdrawerror", protectplayer, ifwithdrawerror)
module.exports = router;